version: '3.9'

services:
  mongo:
    image: mongo
    container_name: moso-app-mongo
    ports:
      - 27017:27017
    restart: always
    #command: --serviceExecutor adaptive

  node-app:
    build: 
      dockerfile: ../../AppointApp_backend
    image: isakhalin/node-vksplanner
#    deploy:
#      mode: replicated
#      replicas: 7
#    resources:
#      limits:
#        cpus: '0.60'
#        memory: 60M
#      reservations:
#        cpus: '0.15'
#        memory: 10M
    container_name: node-vksplanner
    ports:
      - 3005:3005
    restart: always
    env_file: ../../AppointApp_backend/.env

  nginx:
    build: /nginx
    image: isakhalin/moso-app-nginx
    container_name: moso-app-nginx
    ports:
      - 80:80
    restart: always