version: '3.9'

services:
  mongo:
    hostname: mongo
    image: mongo
    container_name: moso-app-mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vksplanner
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
#     - /home/stepanov/vksplanner-mongo/backups:/mongo/backups
      # Скрипты, которые выполняются при создании контейнера:
      #  1. Скрип init.js создает коллекцию и добавляет 2х пользователей(адмиистратора и пользователя для бека)
      - /home/stepanov/vksplanner-mongo/scripts:/docker-entrypoint-initdb.d
      # Байнд каталога для бекапов. Сюда делаются бекапы из контейнера mongo
      - type: bind
        source: /home/stepanov/vksplanner-mongo/backups
        target: /mongo-backups

  node-vksplanner:
    image: isakhalin/node-vksplanner
    container_name: node-vksplanner
    depends_on:
      - mongo
    ports: 
      - 3005:3005
    restart: always
    environment:
      PORT: 3005
      DB_URL: mongodb://vksplanner:738ybfDt@mongo:27017/vksplanner?authSource=vksplanner

  moso-app-nginx:
    image: nginx
    container_name: moso-app-nginx
    volumes:
      - /home/stepanov/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/stepanov/nginx/builds:/builds
    depends_on:
      - node-vksplanner
    ports:
      - 80:80
    restart: always
