version: '3.9'

services:
  mongo:
    image: mongo
    container_name: moso-app-mongo
    ports:
      - "27017:27017"
    restart: always
    #command: --serviceExecutor adaptive

  node-vksplanner:
    image: isakhalin/node-vksplanner
    container_name: node-vksplanner
    depends_on:
      - mongo
    ports: 3005:3005
    restart: always
    environment:
      PORT: 3005
      DB_URL: mongodb://mongo:27017/vksplanner

  moso-app-nginx:
    image: isakhalin/moso-app-nginx
    container_name: moso-app-nginx
    #volumes:
    #  - ./web/app:/app
    #command: node app.js
    depends_on:
      - node-vksplanner
    ports:
      - 80:80
    restart: always