version: '3.9'

services:
  mongo:
    hostname: mongo
    image: mongo
    container_name: cofferium-mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cofferium
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
#     - /home/stepanov/vksplanner-mongo/backups:/mongo/backups
      # Скрипты, которые выполняются при создании контейнера:
      #  1. Скрип init.js создает коллекцию и добавляет 2х пользователей(адмиистратора и пользователя для бека)
      - /home/stepanov/cofferium-mongo/scripts:/docker-entrypoint-initdb.d
      # Байнд каталога для бекапов. Сюда делаются бекапы из контейнера mongo
      - type: bind
        source: /home/stepanov/cofferium-mongo/backups
        target: /mongo-backups

  cofferium-node-app:
    image: isakhalin/cofferium-node-app
    container_name: cofferium-node-app
    depends_on:
      - mongo
    ports:
      - 3005:3005
    restart: always
    environment:
      PORT: 3005
      DB_URL: mongodb://cofferium:63dsf47$38#23t@mongo:27017/cofferium?authSource=cofferium

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /home/stepanov/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/stepanov/nginx/builds:/builds
    depends_on:
      - cofferium-node-app
    ports:
      - 80:80
    restart: always
